import Head from 'next/head'
import { Inter } from '@next/font/google'

import Navbar from '../components/Navbar'
import Landing from '../components/Landing'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Navbar />
      <main className='flex flex-col items-center justify-center min-h-screen'>
        <Landing />
      </main>
    </>
  )
}

export const getStaticProps = async ({ locale }: any) => {
  return {
    props: {
      messages: {
        ...require(`../messages/navbar/${locale}.json`),
        ...require(`../messages/landing/${locale}.json`),
      },
    },
  }
}
