import Head from 'next/head'

import Navbar from '../components/Navbar'
import Landing from '../components/Landing'
import About from '../components/About'
import WhatWeDo from '../components/WhatWeDo'
import OurWork from '../components/OurWork'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>FagusNS 021</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/logo.svg'
        />
      </Head>
      <Navbar />
      <main className='flex flex-col items-center justify-center min-h-screen'>
        <Landing />
        <About />
        <WhatWeDo />
        <OurWork />
        <Contact />
        <Footer />
      </main>
    </>
  )
}

export const getStaticProps = async ({ locale }: any) => {
  return {
    props: {
      messages: {
        ...require(`../messages/navbar/${locale}.json`),
        ...require(`../messages/landing/${locale}.json`),
        ...require(`../messages/about/${locale}.json`),
        ...require(`../messages/what-we-do/${locale}.json`),
        ...require(`../messages/our-work/${locale}.json`),
        ...require(`../messages/contact/${locale}.json`)
      }
    }
  }
}
